### ISSUE TITLE
Where is the output bed file?

### ISSUE THREAD

**Issue by xiekunwhy** [vgl-hub/teloscope#1]
Hi,

When the command line is coplete, there is no bed file output.

/public2/home/sl_qybio/sl_qybio/software/biosoft/teloscope/build/bin/teloscope -f ../08.polish/polish.final.sort.fa -p TTAGGG -w 1000 -s 1000 > teloscope.txt

how to output bed file?

Best,
Kun

**Comment by AldhairMedico** [comment]
Dear Kun, 

I apologize for the delayed response. Please, rerun your code with the latest version and feel free to reopen this issue if you find problems. The -o flag should handle the output paths.

Best,
Jack
